import type {Metadata} from "next";
import "./globals.css";
import {Inter} from "next/font/google";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
    title: "Music Academy",
    description: "Generated by create next app",
};

const inter = Inter({subsets: ["latin"]});

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark ">
        <body className={inter.className}>
        <div className="relative w-full flex items-center justify-center ">
            <Navbar/>
        </div>
        {children}
        </body>
        </html>
    );
}
